### ISSUE TITLE
Rename repository to `bundle-preloading`

### ISSUE THREAD

**Issue by felipeerias** [littledan/resource-bundles#24]
Following issue: https://github.com/WICG/resource-bundles/issues/21 and change https://github.com/WICG/resource-bundles/pull/22, this proposal has changed its focus to subresource preloading using bundles.

The name of this repository remains `resource-bundles`, which is now imprecise and potentially misleading as the proposal outlined here does not describe a new format for building resource bundles.

Rather, it uses the [Web Bundles format](https://github.com/wpack-wg/bundled-responses) already being defined by the [IETF WPACK Working Group](https://datatracker.ietf.org/wg/wpack/about/) to solve the specific use case of preloading resources on a Web site.

A better choice of name for the repository would be **`bundle-preloading`**, since that is the specific use case that this proposal aims to solve.

**Comment by cjtenny** [comment]
Hey @yoavweiss , do you have bits to help us with this? Thanks!

**Comment by yoavweiss** [comment]
@cjtenny - you should have the right bits as well now! :)

**Comment by cjtenny** [comment]
![Unlimited power!](https://media.tenor.co/images/3c875fd531d21486ee7fda8fdc9c9d44/raw)
