### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by codehag** [littledan/resource-bundles#7]
There is a motivation sub-section for Subresource loading with resource bundles but none for the main repository, it is partially covered in "implementation", and touched on in other areas. However there is no "we need to fix this problem or this set of problems" that is easily understood from the readme. 

I think for those who are familiar with what this is trying to solve it may be self evident, but not everyone is or they may not agree with the motivation. Can you add a section to the README?

For example, someone coming from the webpackage area might think this has the same motivation as that project, which lists it as:

> Previous attempts at packaging web resources (e.g. Resource Packages and the W3C TAG's packaging proposal) were motivated by speeding up the download of resources from a single server, which is probably better achieved through other mechanisms like HTTP/2 PUSH, possibly augmented with a simple manifest of URLs a page plans to use. T**his attempt is instead motivated by avoiding a connection to the origin server at all**. It may still be useful for the earlier use cases, so they're still listed, but they're not primary.

But is the goal here the same? (I suspect no, but I think you know the specific motivation better here)

**Comment by littledan** [comment]
The goal is definitely different, more similar to the previous attempts. Thanks for filing this issue; I'll work to improve the explainer here.

**Comment by littledan** [comment]
I've edited the main README file to include some text that @codehag wrote about the motivation. Thanks for your help here!
