### ISSUE TITLE
Clarifying serving.md

### ISSUE THREAD

**Issue by codehag** [littledan/resource-bundles#8]
In the serving document, the proposal opens with

> The resource bundle file format can be used by web servers to improve usability.

What does usability mean here? I would have actually expected an [expansion on this](https://github.com/littledan/resource-bundles/blob/main/subresource-loading.md#for-servers) if we are talking about usability.

The document also covers chunking -- this isn't something that I would think of as covered by usability, so the introductory paragraph threw me off. I would expect the opening to be. I would have expected a dedicated section on serving to be broader than usability. It might also help to pull out the serving parts out of the subresource loading document and link it to here. Maybe starting with something like this?

# Serving Resource Bundles

The Resource bundles proposal seeks to address some of the issues that arise on the web platform when shipping complex application to the client. This segment focuses on how resource bundles address those concerns and what additional benefits may come from using this technique.

And move and expand these sections from subresourcing
* https://github.com/littledan/resource-bundles/blob/main/subresource-loading.md#for-servers
*  (etc, will add others later)

**Comment by littledan** [comment]
Good idea; I've reorganized the md files along these lines.
